name: CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  stack:

    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        stack: ["2.13.1"]
        ghc: ["9.4.7"]

    steps:

    - name: Checkout repo 
      uses: actions/checkout@v3

    - name: Restore from cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          ~/.ghcup
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack${{ matrix.stack }}

    - name: Setup Haskell Stack
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      timeout-minutes: 15
      run: |
        stack build --system-ghc --test --no-run-tests --only-dependencies

    - name: Run tests with coverage
      timeout-minutes: 15
      run: |
        stack test --system-ghc --test --coverage --fast

    - name: Build
      timeout-minutes: 15
      run: |
        stack build --system-ghc --test --no-run-tests

    - name: Generate coverage report
      uses: 8c6794b6/hpc-codecov-action@v3
      with:
        target: stack:haskell-simple-calculator-test
        out: ./codecov.json
        verbose: true

    - name: Send coverage report
      uses: codecov/codecov-action@v3
      with:
        files: ./codecov.json
        fail_ci_if_error: false # optional (default = false)
        verbose: true
